### ISSUE TITLE
[Unnamed Game] I am trying to install KakarotModManager 

### ISSUE THREAD

**Issue by Sithscott** [thesupersonic16/KakarotModManager#2]
It tells me that the game is null even though I own the game. I even put the mod manager in the directory of the exe file on steam.

KMM Info:
    Version: 1.0-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\DRAGON BALL Z KAKAROT\
    Process Level: Administrator
    Game: Unnamed Game

Exception:
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: KakarotModManager
    Function: System.Collections.Generic.List`1[KakarotModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at KakarotModManager.Steam.SearchForGames(String preference)
       at KakarotModManager.App.Main(String[] args)
    InnerException:

**Comment by thesupersonic16** [comment]
Forgot Steam made some changes to some files. Does this work?

[KakarotModManager.zip](https://github.com/thesupersonic16/KakarotModManager/files/6794797/KakarotModManager.zip)

**Comment by Sithscott** [comment]
Works! thank you! You are awesome!
